package p6_11584;
import java.util.Scanner;

public class Main {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		int n = sc.nextInt(),l;sc.nextLine();
		int[] dp;
		String s;
		while(n--!=0) {
			s = sc.nextLine();
			l = s.length();
			dp = new int[l+1];
			dp[1] = 1;
			for(int i = 2; i <= l; i++) {
				dp[i] = dp[i-1] + 1;
				for(int j = 0; j < i; j++) {
					if(if_palindrome(s,j,i-1)) {
						dp[i] = Math.min(dp[j]+1, dp[i]);
					}
				}
			}
			System.out.println(dp[l]);
		}
		sc.close();
	}
	public static Boolean if_palindrome(String str, int s, int e) {
		while(s<e) {
			if(str.charAt(s)!=str.charAt(e)) {
				return false;
			}
			++s;--e;
		}
		return true;
	}
}
//https://cpe.cse.nsysu.edu.tw/cpe/file/attendance/problemPdf/11584.pdf

/*
3
racecar
fastcar
aaadbccb

20
racecar
fastcar
aaadbccb
abbaabba
abbaabbaabba
racecarabc
racecarabcc
racecarabccba
racecarabcracecarabc
dfjlaskdjfsldflsdfadgfdecarabcracecar
sdkllkabsassksdkkkdhskajdfla
sdfkskdkkkllsdflslsfdhskajdflasdfal
abbsbdmsdbmsdmsmdnfmssdfadgfdecarabc
sdfsdiewsjwkkeejwejwkksjdsdkskdjdflaksdflaskfl
skfdhslkdfhlaksfhakfhsfghf
sweasdflsdjflaseksjfdhsjfdhskajdflasdfalksdflwkjashdflasjdflasdflaskdflaksfdsdfksjdfhasfhwusj
sjdjjkjsdkwjerjweksjfdhskajdflasdfalksdflwkjashdflasjdflasdflaskdflaksfdsdfksjdfhasfhwusjdflaksdflaskflskfdhslkdfhlaksfhakfhsfghf
sweasdflsdjflaseksjfdhskajdflasdfalksdflwkjashdflasjdflasdflaskdflaksfdsdfksjdfhasfhwusjdflsadfasdfalksdflwkfiposadfjkasfdjshdfkjhkalsdfjskfdsj
sdfkjksjldfjsdfjsadfjsdfkjsdfhksjadfhksjdhfkadsfksjdfkasdhfklsflxbmvbmvnxzcvnzmxbvnbhsqyweqywetqueyquyetuqyweuqtweryteusdfhasdgfjhsajh
fkjsdfhksjadfhksjdhsdfkjsdfhksjadfhksjdhsdfwueurjsdfhksadhfksjdhflafpsdfiasdfipsifdpsdfipasdfopspodfposdfsipdofiposadfjkasfdjshdfkjhkalsdfjskfdsjfhsdhfkhiuwerhahsdjfshdfhskadfhksjdhsdfwueuradfhksjdhsdfwueurjsdfhksadhfksjdhflafpsdfiasdfipsifdpsdfipasdfopspodfposdfsipdofiposadfjkasfdjshdfkjhkalsdfjskfdsjfhsdhfkhiuwerhahsdjfshdfhskjdfhuwaajsdfhksadhfksjdhflafpsdfiasdfipsifdpsdfipasdfopspodfposdfsipdofiposadfjkasfdjshdfkjhkalsdfjskfdsjfhsdhfkhiuwerhahsdjfshdfhskjdfhuwaajshfdkjsahdfkjahfkjhasdfjkhaksjfhkjshfjwhueafjdhkfdhfkadsfksjdfkasdhfklsfwueurjsdfhksadhfksjdhflafpsdfiasdfipsifdpsdfipasdfopspodfposdfsipdofiposadfjkasfdjshdfkjhkalsdfjskfdsjfhsdhfkhiuwerhahsdjfshdfhskjdfhuwaajshfdkjsahdfkjahfkjhasdfjkhaksjfhkjshfjwhueafjdhkfdhfkadsfksjdfkasdhfklsflxbmvbmvnxzcvnzmxbvnbhsqyweqywetqjdfhuwaajshfdkjsahdfkjahfkjhasdfjkhaksjfhkjshfjwhueafjdhkfdhfkadsfksjdfkasdhfklsflxbmvbmvnxzcvnzmxbvnbhsqyweqywetq

20
kjsdfhksjadf
hksjdhsdfwu
eurjsdfhksadhfksjdhflafpsdfiasdfipsifdpsdf
ipasdfopspodfposdfsipdofiposadfjkas
fdjshdfkjhkalsdfjskfdsjfhsdhfkhiuwerhahsdjfshdfhskjdfhuwaajshfdkjsa
hdfkjahfkjhasdfjkhaksjfhkjshfjwhueafjdhkfdhfkadsfksjdfkasdhfklsflxbmvbmvnxzcvnzmxbvnbhsqyweqywetq
adfhksjdhsdfwueuradfhksjdhsdfwueurjsdfhksadhfksjdhflafpsdfiasdfipsifdpsdfipasdfopspodfposdfsipdofiposad
fjkasfdjshdfkjhkalsdfjskfdsjfhsdhfkhiuwerhahsdjfshdfhskjdfhuwaajsdfhksadhfksjdhflafpsdfiasdfipsifdpsdf
ipasdfopspodfposdfsipdofiposadfjkasfdjshdfkjhkalsdfjskfdsjfhsdhfkhiuwe
rhahsdjfshdfhskjdfhuwaajshfdkjsahdfkjahfkjhasdfjkhaksjfhkjshfjwhueafjdhkfdhfkadsfksjdfkasdhfklsfadfhksjdhsdfkjsdfhksjadfhksjdhsdfwueurjsdfhksadhfksjdhflafpsdfiasdfipsif
dpsdfipasdfopspodfposdfsipdofiposadfjkasfdjshdfkjhkalsdfjskfdsjfhsdhfkhiuwerhahsdjfshdf
hskadfhksjjahfkjhasdfjkhaksjfhkjshfjwhueafjdhkfdhfkadsfksjdfkasdhfklsfwueurj
sdfhksadhfksjdhflafpsdfiasdfipsifdpsdfipasdfopspodfposdfsipdofiposadfjkasfdjshdfkjhdhsdfwueuradfhksjdhsdfwueurjsdfhksadhfksjdhflafpsdfiasdfipsifdpsdfipasdfopspodfposdfsipdofiposadfjkasfdjshdfkjhkalsdfjskfdsjfhsdhfkhiuwerhahsdjfsh
dfhskjdfhuwaajsdfhksadhfksjdhflafpsdfiasdfipsifdpsdfipasdfopspodfposdfsipdofiposadfjkasfdjshdfkj
hkalsdfjskfdsjfhsdhfkhiuwerhahsdjfshdfhskjdfhuwaajshfdkjsahdfkkalsdfjskfsdfsfkuuyyyewuadfhjjhavvcvhdfhsdahsdfsadfhjsdfjsdjcjdcdjbchbayjdahdsfgasjdfgajshchdbjabdsdfsdfjjwerjlweafdjlasjfljsdlcdjndjnfakjsdnfsdjcndjnckadnfkansdfjsndcndjnakdfakdk 
cdjsafdadsfsdfjfasbdjfbsdjfbajsdfbjasdbfjasdbjcbjhdbcjhabdfadsfsdfdjfldfjkdafdddsjfhsdhf
khiuwerhahsdjfshdfhskjdfhuwaajshfdkjsahdfkjahfkjhasdfjkhaksjfhkjshfjwhueafjdhkfdhfkadsfksjdfkassdfsadfweweuriweruyuxbhbchdbcjhabdjfhbadsjbcjhsabdhbacjhbdjcbajdfbjasbdc
hdbchbabddhfklsflxbmvsdfsdfsjdfhskdhkckjdnjndjandfjasd cdbmvnxzcvnzmxbvnbhsqyweqywetqjdfhuwaadfhjjhavvcvhdfhsdahsdfsadfhjsdfjsdjcjdcdjbchbayjdahdsfgasjdfgajshchdbjabdsdfsdfjjwerjlweafdjlasjfjshfdkjsahdfkjahfkjhasdfjkhaksjfhkjshfjwhueafjdhkfdhfkadsfksjdfkasdhfklsflxbmvbmvnxzcvnzmxbvnbhsqyweqywetq
abddhfklsflxbmvsdfsdfsjdfhskdhkckjdnjndjandfjasdcdbmvnxzcvnzmxbvnbhsqyweqywetqjdfhuwaadfhjjhavvcvhdfhsdahsdfsadfhjsdfjsdjcjdcdjbchbayjdahdsfgasjdfgajshchdbjabdsdfsdfjjwerjlweafdjlasjfjshfdkjsahdfkjahfkjhasdfjkhaksjfhkjshfjwhueafjdhkfdhfkadsfksjdfkasdhfklsflxbmvbmvnxzcvnzmxbvzcvnzmxbvnbhsqyweqywetqjdfhuwaadfhjjhavvcvhdfhsdahsdfsadfhjsdfjsdjcjdcdjbchbayjdahdsfgasjdfgajshchdbjabdsdfsdfjjwerjlweafdjlasjfjshfdkjsahdfkjahfkjh
lsflxbmvsdfsdfsjdfhskdhkckjdnjndjandfjasdcdbmvnxzcvnzmxbvnbhsqywvsdfsdfsjdfhskdhkckjdnjndjandfjasdcdbmvnxzcvnzmxbvnbhsqyweqywetqjdfhuwaadfhjjhavvcvhdfhsdahsdfsadfhjsdfjvsdfsdfsjdfhskdhkckjdnjndjandfjasdcdbmvnxzcvnzmxbvnbhsqyweqywetqjdfhuwaadfhjjhavvcvhdfhsdahsdfsadfhjsdfjsdjcjdcdjbchbayjdahdsfsdjcjdcdjbchbayjdahdsfgaseqywetqjdfhuwaadfhjjhavvcvhdfhsdahsdfsadfhjsdfjsdjcjdcdjbchbayjdahdsfgasjdfgajshchdbjabdsdfsdfjjwerjlweafdjlasjfjshfdkjsahdfkskdhkckjdnjndjandfjasdcdbmvnxzcvnzmxbvnbhsqywvsdfsdfsjdfhskdhkckjdnjndjandfjasdcdbmvnxzcvnzmxbvnbhsqyweqywetqjdfhuwaadfhjjhavvcvhdfhsdahsdfsadfhjsdfjvsdfsdfsjdfhskdhkckjdnjndjandfjasdcdbmvnxzcvnzmxbvnbhsqyweqyfjasdcdbmvnxzcvnzmxbvnbhsqyweqywetqjdfhuwaadfhjjhavvcvhdfhsdahsdfsadfhjsdfjvsdfsdfsjdfhskdhkckjdnjndjandfjasdcdbmvnxzcvnzmxbvnbhsqyweqywetqjdfhuwaadfhjjhavvcvhdfhsdahsdfsadfhjsdfjsdjcjdcdjbchbayjdahdsfsdjcjdcdjbchbayjdahdsfgaseqywetqjdfhuwaadfhjjhavvcvhdfhsdahsdfsadfhjsdfjsdjcjdcdjbchbayjdahdsfgasjdfgajshchdbjabdsdfsdfjjwerjlweafdjlasjfjsh

*/